name: Publish Poetry Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    environment: main
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build the package
      run: poetry build

    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish --username __token__ --password "${{env.PYPI_API_TOKEN}}"